### ISSUE TITLE
Second Chance works with RW lock

### ISSUE THREAD

**Issue by yoheiueda** [josephlewis42/go-multicache#9]
If I understand [the Go memory model](https://golang.org/ref/mem) correctly, I think the Second Chance algorithm works with RW lock.

Is it possible to change the return value of `UpdatesOnRetrieved()` in `second_chance.go
` to `false` for better concurrent performance?

https://github.com/josephlewis42/multicache/blob/4bf8497e085400dc9a5eb9327e2a00e80563de13/second_chance.go#L49-L51

`item.Tag = 1` is always followed by `mc.lock.RUnlock()`. Every gorouting that holds the read lock stores the same value `1`.

https://github.com/josephlewis42/multicache/blob/4bf8497e085400dc9a5eb9327e2a00e80563de13/second_chance.go#L53-L57

`currentItem.Tag == 0` is always proceded by `mc.lock.Lock()`.  The value is `0` or `1`. 

https://github.com/josephlewis42/multicache/blob/4bf8497e085400dc9a5eb9327e2a00e80563de13/second_chance.go#L32-L47

`item.Tag = 1` happens before `mc.lock.RUnlock()` , `mc.lock.RUnlock()` happens before `mc.lock.Lock()`, and `mc.lock.Lock()` happens before `currentItem.Tag == 0`.

**Comment by josephlewis42** [comment]
@yoheiueda nice find! Yes, that seems like it would work to me.

I'd be happy to merge a PR if you want to make one, but maybe do it by creating a "Fast Second Chance" and leave the original there? That way they can be compared in the benchmarks and the original will be "correct" according to the method names while `fast_second_chance` will be an improvement that takes advantage of the current implementation.
